# Dependencies
markdown:         kramdown
highlighter:      rouge
gems: [jekyll-gist, jekyll-paginate]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Mhynlo
tagline:          'Mhynlo blog'
description:      'Playing games<br/>Developing stuff'
url:              http://mhynlo.io
baseurl:          /

author:
  name:           'Mhynlo'
  email:          'mhynlo@mhynlo.io'
  # url:            https://twitter.com/mhynlo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mhynlo/mhynlo.io
